apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: web
spec:
  containers:
    - name: backend
      image: centos
      command: [ "/bin/bash", "-ce", "tail -f /dev/null" ]
      ports:
        - containerPort: 8080